//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Configuration;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.EntityClient;
    using System.Data.SqlClient;
    using System.IO;

    public partial class bayer_Entities : DbContext
    {
        public bayer_Entities()
            : base(ConnectionString.GetConnection())
        {
        }
    
        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    throw new UnintentionalCodeFirstException();
        //}
    
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<Activity> Activities { get; set; }
    }

}
